# Generated by Django 3.1.6 on 2021-03-08 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Описание товара')),
                ('category', models.CharField(choices=[('other', 'Разное'), ('flowers ', 'Цветы'), ('toys', 'Игрушки'), ('dishes', 'Посуда')], default='other', max_length=40, verbose_name='Категория')),
                ('balance', models.PositiveIntegerField(default=1, verbose_name='Остаток')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
    ]
